restylers_version: stable
auto: true
pull_requests: false
restylers:

  - clang-format:
      image: restyled/restyler-clang-format:12.0.1
      include:
        - "!tests/shell/gen/**/*"
        - "!**/*.js"

  - prettier:
      image: restyled/restyler-prettier:v2.3.2
  - prettier-markdown:
      image: restyled/restyler-prettier:v2.3.2
      arguments: []
  - shfmt:
      image: restyled/restyler-shfmt:v3.3.1
      arguments:
        - -s
        - -sr
