restylers_version: dev
auto: true
pull_requests: false
restylers:

  - clang-format:
      image: restyled/restyler-clang-format:13.0.1
      include:
        - "!tests/shell/gen/**/*"
        - "!**/*.js"
  - prettier:
      image: restyled/restyler-prettier:v2.3.2
  - prettier-markdown:
      image: restyled/restyler-prettier:v2.3.2
      arguments: []
  - shfmt:
      image: restyled/restyler-shfmt:v3.3.1
      arguments:
        - -s
        - -sr
  - google-java-format:
      image: 'restyled/restyler-google-java-format:v1.9'
      command:
        - google-java-format
        - '--replace'
      include:
        - '**/*.java'
